[project]
name = "gridhub-mock"
version = "0.1.0"
description = "GridHub Mock Server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "uvicorn ~= 0.34.0",
    "fastapi ~= 0.115.11"
]
